### ISSUE TITLE
Release 0.9.0 for Ruby 4.0?

### ISSUE THREAD

**Issue by ronaldtse** [matsadler/magnus#173]
First of all, THANK YOU @matsadler for this wonderful work.

Is there a plan to release 0.9.0 on crates.io which is needed for Ruby 4.0?

**Comment by ankane** [comment]
Hi @ronaldtse, the current release should work with Ruby 4.0 (I'm using it for a number of gems). What error are you seeing?

**Comment by cyrilleberger** [comment]
Hi @ankane on latest Fedora, which seem to have ruby 4.0.1, I am getting:

```
error[E0432]: unresolved import `rb_sys::rb_data_type_struct__bindgen_ty_1`
  --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:21:11
   |
21 |     self, rb_data_type_struct__bindgen_ty_1, rb_data_type_t, rb_gc_writebarrier,
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `rb_data_type_struct__bindgen_ty_1` in the root
error[E0560]: struct `rb_data_type_struct` has no field named `wrap_struct_name`
   --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:346:13
    |
346 |             wrap_struct_name: self.name.as_ptr() as _,
    |             ^^^^^^^^^^^^^^^^ `rb_data_type_struct` does not have this field
    |
    = note: available fields are: `_address`
error[E0560]: struct `rb_data_type_struct` has no field named `function`
   --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:347:13
    |
347 |             function: rb_data_type_struct__bindgen_ty_1 {
    |             ^^^^^^^^ `rb_data_type_struct` does not have this field
    |
    = note: available fields are: `_address`
error[E0560]: struct `rb_data_type_struct` has no field named `parent`
   --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:354:13
    |
354 |             parent: ptr::null(),
    |             ^^^^^^ `rb_data_type_struct` does not have this field
    |
    = note: available fields are: `_address`
error[E0560]: struct `rb_data_type_struct` has no field named `data`
   --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:355:13
    |
355 |             data: ptr::null_mut(),
    |             ^^^^ `rb_data_type_struct` does not have this field
    |
    = note: available fields are: `_address`
error[E0560]: struct `rb_data_type_struct` has no field named `flags`
   --> /home/notroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.8.2/src/typed_data.rs:356:13
    |
356 |             flags,
    |             ^^^^^ `rb_data_type_struct` does not have this field
    |
    = note: available fields are: `_address`
Some errors have detailed explanations: E0432, E0560.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `magnus` (lib) due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
make[2]: *** [CMakeFiles/_cargo-build_gqliterb.dir/build.make:70: CMakeFiles/_cargo-build_gqliterb] Error 101
make[1]: *** [CMakeFiles/Makefile2:486: CMakeFiles/_cargo-build_gqliterb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ankane** [comment]
What version of `rb-sys` are you on, and does updating `rb-sys` fix it? (it looks like the same error as #174)

**Comment by cyrilleberger** [comment]
Thanks for the quick answer @ankane! Updating `rb-sys` did the trick for me, I guess I shoud have checked closed issues first.

**Comment by hsbt** [comment]
Ruby 4.1 (current `ruby-head`) needs this fix released too. Building `magnus` 0.8.2 there fails with `missing field handle_weak_references in initializer of rb_data_type_struct__bindgen_ty_1` plus a `reserved` array length mismatch, because ruby/ruby@6939f03 grew that struct. `main` already handles this, and pointing the dependency at the git branch makes `cargo test` pass for me, so whatever version carries the fix would unblock it.

This reaches users through the `bundle gem --ext=rust` template in RubyGems, which pins `magnus = "0.8.2"`.

**Comment by gjtorikian** [comment]
@matsadler would you consider cutting a new release for this and other fixes? Ruby 4.1 is a few months away, I think this issue has been present since https://github.com/matsadler/magnus/pull/164#issuecomment-4059433370

If it's helpful to copy, I have a set of [GitHub workflows](https://github.com/gjtorikian/actions) that just automate the release process using OIDC; it's based on [release-please](https://github.com/googleapis/release-please). The idea is that PRs use conventional starts (`fix`, `feat`, `feat!`) for patch, minor, and major releases. All I do is merged a single PR and the entire release process is automated; here's [an example](https://github.com/gjtorikian/commonmarker/pull/479).

**Comment by matsadler** [comment]
I've released [0.9](https://github.com/matsadler/magnus/releases/tag/0.9.0).

**Comment by ronaldtse** [comment]
Thank you @matsadler !
